[package]
name = "hv-stampede"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.8.0", features = ["allocator_api", "boxed"] }
spin = "0.9.2"
