[package]
name = "hv"
version = "0.2.0"
edition = "2021"

[features]
lua54 = ["lua/lua54"]
lua53 = ["lua/lua53"]
lua52 = ["lua/lua52"]
lua51 = ["lua/lua51"]
luajit = ["lua/luajit"]
vendored = ["lua/vendored"]
module = ["lua/module"]

glfw = ["input/glfw"]
parry3d = ["lua/parry3d"]

[dependencies]
alchemy = { path = "crates/hv-alchemy", package = "hv-alchemy" }
anyhow = "1.0.44"
ecs = { path = "../hecs", package = "hecs" }
ecs-derive = { path = "crates/hv-ecs-derive", package = "hv-ecs-derive" }
fs = { path = "crates/hv-filesystem", package = "hv-filesystem" }
guarded_borrow = { path = "crates/hv-guarded-borrow", package = "hv-guarded-borrow", features = ["std", "hecs"] }
lua = { path = "crates/hv-lua", package = "hv-lua", features = ["hv-reexport", "nalgebra", "send", "macros"] }
math = { path = "crates/hv-math", package = "hv-math" }
petgraph = "0.6.0"
sync = { path = "crates/hv-sync", package = "hv-sync" }
thiserror = "1.0.30"
yaks = { path = "../yaks" }
input = { path = "crates/hv-input", package = "hv-input" }
timer = { path = "crates/hv-timer", package = "hv-timer" }
stampede = { path = "crates/hv-stampede", package = "hv-stampede" }
