[package]
name = "hv"
version = "0.1.0"
edition = "2021"

[features]
lua54 = ["lua/lua54"]
lua53 = ["lua/lua53"]
lua52 = ["lua/lua52"]
lua51 = ["lua/lua51"]
luajit = ["lua/luajit"]
vendored = ["lua/vendored"]
module = ["lua/module"]

[dependencies]
anyhow = "1.0.44"
alchemy = { path = "crates/hv-alchemy", package = "hv-alchemy" }
ecs = { path = "../hecs", package = "hecs" }
yaks = { path = "../yaks" }
fs = { path = "crates/hv-filesystem", package = "hv-filesystem" }
lua = { path = "crates/hv-lua", package = "hv-lua", features = ["hv-reexport"] }
sync = { path = "crates/hv-sync", package = "hv-sync" }
petgraph = "0.6.0"
thiserror = "1.0.30"
