[workspace]
members = [
    "hecs",
    "hv/crates/hv-alchemy",
    "hv/crates/hv-boxed",
    "hv/crates/hv-ecs-derive",
    "hv/crates/hv-filesystem",
    "hv/crates/hv-lua-derive",
    "hv/crates/hv-lua",
    "hv/crates/hv-lua/examples/module",
    "hv/crates/hv-lua/tests/module",
    "hv/crates/hv-math",
    "hv/crates/hv-sync",
    "hv/crates/hv-vfs",
    "hv",
    "projects/scratch",
    "yaks",
]