[workspace]
members = [
    "altar",
    "hecs",
    "tiled",
    "hv/crates/hv-alchemy",
    "hv/crates/hv-boxed",
    "hv/crates/hv-ecs-derive",
    "hv/crates/hv-event-channel",
    "hv/crates/hv-filesystem",
    "hv/crates/hv-guarded-borrow",
    "hv/crates/hv-input",
    "hv/crates/hv-lua-derive",
    "hv/crates/hv-lua",
    "hv/crates/hv-lua/examples/module",
    "hv/crates/hv-lua/tests/module",
    "hv/crates/hv-math",
    "hv/crates/hv-stampede",
    "hv/crates/hv-sync",
    "hv/crates/hv-timer",
    "hv/crates/hv-vfs",
    "hv",
    "resources",
    "yaks",
]