[package]
name = "hv-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { git = "https://github.com/sdleffler/egui", rev = "26d7" }
hv-lua = { path = "../../../hv-lua" }
hv-math = { path = "../hv-math" }
hv-input = { path = "../hv-input" }
