[package]
name = "hv-sync"
version = "0.1.0"
edition = "2021"

[features]
track-leases = []
default = []

[dependencies]
hecs = { path = "../../../hecs" }
hv-guarded-borrow = { path = "../hv-guarded-borrow" }
