[package]
name = "hv-sync"
version = "0.1.0"
edition = "2021"

[features]
track-leases = ["slab"]
default = ["track-leases"]

[dependencies]
hecs = { path = "../../../hecs" }
hv-guarded-borrow = { path = "../hv-guarded-borrow" }
slab = { version = "0.4.5", optional = true }
spin = "0.9.2"
