[package]
name = "altar"
version = "0.1.0"
authors = ["Shea 'Decibel' Leffler <shea@errno.com>", "Maxim Veligan <maximveligan@gmail.com>"]
edition = "2021"

[dependencies]
hv = { path = "../hv" }
luminance = "0.44.1"
resources = "1.1.0"
