[package]
name = "altar"
version = "0.1.0"
authors = ["Shea 'Decibel' Leffler <shea@errno.com>", "Maxim Veligan <maximveligan@gmail.com>"]
edition = "2021"

[features]
glfw-windowing = ["glfw", "luminance-glfw", "hv/glfw", "luminance-windowing", "windowed"]
windowed = []
default = ["glfw-windowing"]

[dependencies]
glfw = { version = "0.41", optional = true }
hv = { path = "../hv" }
luminance = "0.44.1"
luminance-glfw = { version = "0.16.0", optional = true }
luminance-windowing = { version = "0.10.0", optional = true }
resources = "1.1.0"
